language: node_js
node_js:
- '10'
branches:
  only:
  - master
  # npm version tags
  - /^v\d+\.\d+\.\d+$/
before_script:
- yarn lint:git
- yarn lint:md
- yarn lint:js
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  edge: true # opt in to dpl v2
  on:
    tags: true
    repo: CrowdStrike/monorepo-next
